# Generated by Django 4.1.7 on 2023-04-05 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliodetails',
            name='links',
        ),
    ]
