# Generated by Django 4.1.7 on 2023-04-05 14:23

import any_urlfield.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_remove_portfoliodetails_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfoliodetails',
            name='url',
            field=any_urlfield.models.fields.AnyUrlField(max_length=300, null=True, verbose_name='URL'),
        ),
    ]
