# Generated by Django 4.1.7 on 2023-04-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_portfoliodetails_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfoliodetails',
            name='summary',
            field=models.CharField(max_length=254),
        ),
    ]
